pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Prep') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd api && rspec'
            }
        }
        stage('UAT') {
            steps {
                echo 'Aguardando testes de aceitação.'
                input message: 'Podemos ir para produção?'
            }
        }
        stage('Prod') {
            steps {
                echo 'Api pronta para produção :)'
            }
        }
    }
    post {
        always {
            junit 'api/logs/report.xml'
        }
    }
}
